# Imagen con Java 17 (requerido por Spring Boot moderno)
FROM gradle:8.5-jdk17 AS build

WORKDIR /app

# Copiar código
COPY . .

# Dar permisos al gradlew
RUN chmod +x ./gradlew

# Construir el proyecto
RUN ./gradlew build -x test

# Imagen final
FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

# Copiamos el JAR generado
COPY --from=build /app/build/libs/*.jar app.jar

EXPOSE 8088

CMD ["java", "-jar", "app.jar"]
